# frozen_string_literal: true

require "securerandom"
require "uri"

module SparrowAuth
  # Signing somebody in with something sent to their email address.
  #
  #   request_id = SparrowAuth::SignIn.request(
  #     email: params[:email], ip: request.remote_ip, base_url: request.base_url
  #   )
  #
  #   account = SparrowAuth::SignIn.redeem(
  #     code: params[:code], request_id: cookies.encrypted[:sparrow_auth_otp_request],
  #     ip: request.remote_ip
  #   )
  #
  # A code or a link, whichever this application chose -- see
  # SparrowAuth::Configuration#emailed_sign_in. ONE seam for both, deliberately:
  # everything below applies whichever was asked for, and two entry points would
  # mean two places to get each of it right. `redeem` is the code path only,
  # because a link is redeemed by opening it, which Rodauth handles.
  #
  # This is here rather than in a controller because SparrowKit ships no
  # end-user pages: the sign-in screen belongs to the application, generated by
  # `rails generate sparrowkit:screens sign_in` and owned by whoever generated
  # it. What must NOT belong to them is any of the below.
  #
  # Almost none of this is about signing in. It is about not answering a
  # question nobody asked -- whether an address has an account -- and the ways
  # to leak that answer are not obvious:
  #
  #   * four different situations, one response, one sentence on screen;
  #   * a cookie set in every branch, including the ones that send no code, so
  #     its presence cannot tell the branches apart;
  #   * a delivery failure swallowed into the same response, because a provider
  #     having a bad day must not become an oracle;
  #   * the account created when a code is REDEEMED, never when one is issued,
  #     because anybody can ask for a code for any address;
  #   * rate limits on the address and on the caller, both.
  #
  # A page that got any one of those wrong would look exactly like a page that
  # got them right. That is the argument for the seam being here.
  module SignIn
    # How long a request id is good for. Matches the cookie the caller sets.
    REQUEST_WINDOW = 15.minutes

    module_function

    # Ask for whatever this application sends. Returns the request id for the
    # caller's cookie.
    #
    # ALWAYS returns an opaque string, and that is the API's most important
    # property. Whether a code was sent, a link was sent, an explanation was
    # sent, nothing was sent because the address has no account, or nothing was
    # sent because the caller is over budget -- every one of them comes back
    # looking the same.
    #
    # It returned nil when over budget for about an hour, and that was a bug
    # waiting to be written by whoever called it next: any caller branching on
    # nil -- a different flash, a different redirect, a 429 -- turns the rate
    # limiter into the enumeration oracle the rest of this file exists to
    # prevent. The budget still stops the mail. It just does not announce that
    # it did.
    #
    # The rate limit is asked BEFORE the mechanism is looked at, so a link and a
    # code spend the same budget. Rodauth's email_auth has a resend guard of its
    # own -- 300 seconds, per account -- and it is a courtesy rather than a
    # defence: it says nothing about the caller, so it does not stop somebody
    # walking an address list from one IP.
    # `base_url` is where this application answers -- `request.base_url` from
    # the caller. It used to be a whole `verify_url` the caller assembled, and
    # that was one more thing for somebody to get subtly wrong in a file they
    # own: every URL this needs is now built here, from the one value only the
    # request can supply.
    def request(email:, ip:, base_url: nil)
      address = OneTimeCode.normalize_email(email)
      return SecureRandom.hex(32) if address.blank?

      within_budget = RateLimiter.allow!(
        "otp_send:email" => address,
        "otp_send:ip" => ip
      )
      return SecureRandom.hex(32) unless within_budget

      issue(address, base_url: base_url)
    end

    # Redeem a code. Returns the Account, or raises InvalidCode.
    #
    # Every refusal is InvalidCode with one message -- absent, wrong, expired,
    # already used, redeemed under a different request id, past the attempt cap,
    # or belonging to an account that has never verified. Telling somebody which
    # wall they hit tells them whether to keep going.
    def redeem(code:, request_id:, ip:)
      raise InvalidCode unless RateLimiter.allow!("otp_verify:ip" => ip)

      email = OneTimeCode.redeem!(request_id: request_id, code: code.to_s.strip)
      account = Account.find_by_email(email) || create_account_from_code(email)

      # An account that exists but has never verified is refused here, and got
      # no code in the first place. Verifying it on the strength of this code
      # would be the wrong repair: somebody registered that address with a
      # password and never proved they could read the mailbox, so signing its
      # real owner in would hand them an account whose password a stranger
      # chose.
      raise InvalidCode unless account&.verified?

      account
    end

    # The four situations, and the one response.
    #
    # This is the settled resolution of a real tension: OWASP requires the
    # response to be uniform and is silent on the resulting confusion. The
    # answer the industry landed on is to move the explanation to the one
    # channel that proves ownership of the address. The screen says the same
    # sentence to everybody; the mailbox gets the truth.
    def issue(address, base_url:)
      account = Account.find_by_email(address)

      if account.nil? && signup_by_email?
        send_the_way_in(address, base_url)
      elsif account.nil?
        # An address with no account has nowhere to go: either this application
        # turned signup off, or it sends links, which cannot make an account --
        # see signup_by_email?. Saying which on screen would answer the
        # enumeration question.
        Mailer.no_account(email: address).deliver_now
        SecureRandom.hex(32)
      elsif !account.verified?
        # The case that would otherwise strand a real person: registered, never
        # clicked the link, now told their code is invalid with no way to work
        # out why. They get the thing that unblocks them.
        Mailer.verification_needed(email: address, url: verify_url(base_url)).deliver_now
        SecureRandom.hex(32)
      else
        send_the_way_in(address, base_url)
      end
    rescue SparrowMail::Error => e
      # Swallowed into the uniform response. A delivery failure answering
      # differently would be an enumeration oracle of its own, and one that only
      # appears when a provider is having a bad day.
      #
      # Logged without the body, per sparrow_mail's first rule: the body is the
      # code.
      SparrowAuth.logger&.warn(
        "[sparrow_auth] otp_send_failed category=#{e.respond_to?(:category) ? e.category : "unknown"}"
      )
      SecureRandom.hex(32)
    end

    # Whether an address nobody has yet can become an account by asking to sign
    # in.
    #
    # `signup_with_code` says whether the application wants that. The mechanism
    # says whether it is possible, and with links it is not.
    #
    # A code can create an account because the account is made when the code is
    # REDEEMED -- by which point somebody has proved they can read the mailbox.
    # A link cannot, because Rodauth hangs the link's key on an account row: the
    # account would have to exist before the mail went out, which would let
    # anybody create an account for any address by typing it into a form. That
    # is the enumeration and spam surface this whole file exists to avoid, and
    # it is not worth reopening for the convenience of one signup path.
    #
    # So with links selected, new people arrive by invitation or through
    # create-account, and an address nobody knows gets the same "no account"
    # mail it would get with signup turned off. The control panel says this
    # beside the choice, because it is a real difference between the two and not
    # a detail.
    def signup_by_email?
      SparrowAuth.config.signup_with_code && !SparrowAuth.config.emailed_sign_in_link?
    end

    # Where somebody is sent to ask for a new confirmation email. Built here
    # from the base URL and the configured prefix, because those two are the
    # only things it depends on and both are already known.
    def verify_url(base_url)
      return nil if base_url.blank?

      "#{base_url}#{SparrowAuth.config.path_prefix}/verify-account-resend"
    end

    # One of two, and the only place the choice is made.
    def send_the_way_in(address, base_url)
      if SparrowAuth.config.emailed_sign_in_link?
        send_link(address, base_url)
      else
        send_code(address)
      end
    end

    def send_code(address)
      record = OneTimeCode.issue(email: address)
      Mailer.sign_in_code(email: address, code: record.code).deliver_now
      record.request_id
    end

    # The link half, asked of Rodauth through an internal request rather than by
    # building a key here.
    #
    # Rodauth generates the key, stores it, sets the deadline, re-sends the
    # existing one rather than issuing a second, and sends the mail through the
    # send_email_auth_email block in rodauth_main.rb. None of that is
    # reimplemented, which is the point: the parts of a sign-in link that are
    # easy to get subtly wrong are the parts somebody else has already got
    # right.
    #
    # The request id it returns belongs to us, not to Rodauth. It is the
    # caller's cookie value and is deliberately unrelated to the key in the
    # link -- the key travels by email and the cookie does not, and tying them
    # together would put half of one into the other.
    def send_link(address, base_url)
      rodauth_class.email_auth_request(login: address, env: internal_env(base_url))
      SecureRandom.hex(32)
    rescue Rodauth::InternalRequestError => e
      # Rodauth raises rather than returning for anything it will not do -- an
      # account it cannot find, one that is closed. Every one of those is a
      # branch `issue` has already decided not to distinguish, so it comes back
      # looking like every other outcome and the reason goes to the log.
      SparrowAuth.logger&.warn("[sparrow_auth] sign_in_link_refused reason=#{e.reason.inspect}")
      SecureRandom.hex(32)
    end

    # The Rodauth class the application is actually running, which is NOT
    # SparrowAuth::RodauthMain.
    #
    # Roda's rodauth plugin configures a SUBCLASS of whatever auth class it is
    # given, and the internal-request methods are defined on the class that was
    # configured. Calling RodauthMain.email_auth_request therefore raises
    # NoMethodError on a class whose feature list plainly includes
    # :internal_request -- which reads like the feature not working rather than
    # like asking the wrong object.
    def rodauth_class
      ::Rodauth::Rails.app.rodauth!(nil)
    end

    # The host this application answers on, handed to Rodauth as a Rack
    # environment.
    #
    # An internal request has no request to read a host from, and Rodauth says
    # so plainly: it raises "must set domain in configuration, as it cannot be
    # determined from internal request". A link with no host in it is not a
    # link, so this supplies one from the real request the caller is already
    # inside — which is also the only way an application on two domains gets a
    # link back for the one somebody actually typed.
    def internal_env(base_url)
      uri = URI.parse(base_url.to_s)
      raise Error, "SparrowAuth::SignIn needs base_url to build a sign-in link" if uri.host.nil?

      {
        "HTTP_HOST" => [uri.host, uri.port].compact.join(":"),
        "SERVER_PORT" => uri.port,
        "rack.url_scheme" => uri.scheme
      }
    end

    # A verified account with no password, made because somebody redeemed a code
    # sent to that address.
    #
    # Verified, because redeeming the code IS the proof -- the same proof the
    # confirmation link asks for, obtained the same way, and already done by the
    # time this runs. No password, because none was ever needed.
    def create_account_from_code(email)
      return nil unless SparrowAuth.config.signup_with_code

      account = Account.create!(email: email, status_id: Account::VERIFIED)

      # Fires here as it would on the link path. An application provisioning on
      # verification must not care which road the account arrived by.
      SparrowAuth.run_hook(:after_verification, account)

      account
    rescue ActiveRecord::RecordNotUnique
      # Two codes for one new address, redeemed at once. Whichever insert lost
      # the race reads the row the winner made.
      Account.find_by_email(email)
    end
  end
end
